server:
  port: 8080

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/productdb_ud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888
  zipkin:
    base-url: http://127.0.0.1:9411/

management:
  tracing:
    sampling:
      probability: 1.0