server:
  port: 8080

spring:
  application:
    name: service-registry
  datasource:
    url: jdbc:mysql://localhost:3306/productdb_ud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update