
server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb_ud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888
  zipkin:
    base-url: http://127.0.0.1:9411/

#We are fetching it from config server now
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
management:
  tracing:
    sampling:
      probability: 1.0
