spring:
  application:
    name: OrderService

server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb_ud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
