spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: main
          uri: https://github.com/akash8993/config-server-repo-microservice2

server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

